# Processor frequency.
F_CPU = 16000000

# Target file name (without extension).
TARGET = tx

# Source files
SRC = ${TARGET}.c \
	../../spooky_encoder.c \

####
include ../mk/common.mk
include ../mk/avrdude_config.mk
include ../mk/atmega328p.mk
